### ISSUE TITLE
Can't clone repo

### ISSUE THREAD

**Issue by stobias123** [Storj/storj-sdk#29]
`git clone https://github.com/Storj/storj-sdk.git --recursive`
Gives me an error on the bridge-gui submodule when cloning. 
```
error: no such remote ref 52cc3640da37abd251601a85985dbe9b06aa6f87
Fetched in submodule path 'bridge-gui/bridge-gui', but it did not contain 52cc3640da37abd251601a85985dbe9b06aa6f87. Direct fetching of that commit failed.
```

Maybe this is fixable on my end through some git wizardry, I just don't know how. Any help would be cool :)

**Comment by mobyvb** [comment]
I ran into this problem last week and @phutchins helped me through it. I forgot the git wizardry, but I went ahead and updated the `bridge-gui` submodule so this won't happen when you clone. 

I'm about to make a PR for it, but in the meantime you should be able to run
```$ git clone -b bridge-gui-fix https://github.com/mobyvb/storj-sdk.git --recursive```
to get the SDK. If you do this, your git remote will point toward my fork of the repository (`mobyvb/storj-sdk`), and not the Storj one (`Storj/storj-sdk`).

To fix this, run the following:
```
$ git remote rename origin mobyvb
$ git remote add origin git@github.com:Storj/storj-sdk.git
$ git remote remove mobyvb
```

**Comment by stobias123** [comment]
One more - What is this file? ` bridge-gui/bridge-gui-vue/dist`
Getting a failure to build with the below error. I just put a dummy file there in the meantime...
```
Step 2/8 : COPY ./bridge-gui-vue/dist /var/www/
ERROR: Service 'bridge-gui-vue' failed to build: lstat bridge-gui-vue/dist: no such file or directory
```

**Comment by phutchins** [comment]
We've fixed the broken reference in bridge-gui so you shouldn't have that issue any longer.

Also, I've added the dist directory to the bridge-gui-vue project so the Docker build will be able to create it's static files. This directory exists so that the docker build has a place to output it's static files after the build. Those files are used by the container built by the storj-sdk which serves those files up via an nginx instance.

Closing this issue as we've tested from a fresh clone and all looks well.

If you have any other issues @stobias123, please let us know. Thanks for your input! We're working hard to make the SDK easier to use little by little...
